# Generated by Django 3.2 on 2022-04-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='message',
            field=models.TextField(max_length=254),
        ),
    ]
